### ISSUE TITLE
Error in README.md

### ISSUE THREAD

**Issue by 31Sanskrati** [31Sanskrati/Python_Projects#11]
### Issue:

In how to contribute, this is given wrong, as it is used for files not folders.
`5. [your-project-folder-name](https://github.com/31Sanskrati/Python_Projects/blob/main/<your-project-folder-name>)`

The correct way will be
`5. [your-project-folder-name](https://github.com/31Sanskrati/Python_Projects/tree/main/<your-project-folder-name>)`

### What to do:
Update the wrong code with the correct one

**Comment by Wahid7852** [comment]
done.
