### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by 31Sanskrati** [31Sanskrati/Python_Projects#2]
Tasks to be perform:

- [x] Change General_Info to Why_This_Repo?
- [x] Update content of Why_This_Repo?
- [x] Add more details in Setup
- [x] Add contribution guide

**Comment by y4sssh** [comment]
I want to work on this Readme file

**Comment by swaraj4410** [comment]
ok sure . what you wanna do?

**Comment by y4sssh** [comment]
I need to update the readme.
